/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChippitIndexRouteImport } from './routes/chippit.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ChippitOnboardingRouteImport } from './routes/chippit.onboarding'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppCallRouteImport } from './routes/app.call'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/app.employees.$employeeId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChippitIndexRoute = ChippitIndexRouteImport.update({
  id: '/chippit/',
  path: '/chippit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ChippitOnboardingRoute = ChippitOnboardingRouteImport.update({
  id: '/chippit/onboarding',
  path: '/chippit/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/call': typeof AppCallRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/chippit/onboarding': typeof ChippitOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/chippit/': typeof ChippitIndexRoute
  '/app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/call': typeof AppCallRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/chippit/onboarding': typeof ChippitOnboardingRoute
  '/app': typeof AppIndexRoute
  '/chippit': typeof ChippitIndexRoute
  '/app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/call': typeof AppCallRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/chippit/onboarding': typeof ChippitOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/chippit/': typeof ChippitIndexRoute
  '/app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/call'
    | '/app/employees'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/settings'
    | '/chippit/onboarding'
    | '/app/'
    | '/chippit/'
    | '/app/employees/$employeeId'
    | '/app/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/call'
    | '/app/employees'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/settings'
    | '/chippit/onboarding'
    | '/app'
    | '/chippit'
    | '/app/employees/$employeeId'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/call'
    | '/app/employees'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/settings'
    | '/chippit/onboarding'
    | '/app/'
    | '/chippit/'
    | '/app/employees/$employeeId'
    | '/app/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChippitOnboardingRoute: typeof ChippitOnboardingRoute
  ChippitIndexRoute: typeof ChippitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chippit/': {
      id: '/chippit/'
      path: '/chippit'
      fullPath: '/chippit/'
      preLoaderRoute: typeof ChippitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/chippit/onboarding': {
      id: '/chippit/onboarding'
      path: '/chippit/onboarding'
      fullPath: '/chippit/onboarding'
      preLoaderRoute: typeof ChippitOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/call': {
      id: '/app/call'
      path: '/call'
      fullPath: '/app/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/employees/$employeeId': {
      id: '/app/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/app/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCallRoute: typeof AppCallRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppInboxRoute: typeof AppInboxRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCallRoute: AppCallRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppInboxRoute: AppInboxRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChippitOnboardingRoute: ChippitOnboardingRoute,
  ChippitIndexRoute: ChippitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
